package com.project.interviewai.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Response DTO for a single interview question generated by AI.
 * Sent back to the frontend when the user requests the next question.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class QuestionResponse {

    private Long questionId;
    private String questionText;
    private String questionType;    // TECHNICAL, BEHAVIORAL, SYSTEM_DESIGN, CODING
    private Integer questionNumber; // e.g., 3 of 10
    private Integer totalQuestions;
}
